language: scala
addons:
  chrome: stable
jdk:
  - openjdk11
dist: bionic
env:
  - IS_JVM=1
  - IS_JS=1
  - IS_NATIVE=1
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
before_install:
  - [[ -n $IS_NATIVE ]] && bash project/travis_setup.sh
before_script:
  - [[ -n $IS_JS ]] && nvm install 10 # nodejs < 10 fails finding URL class
  - [[ -n $IS_NATIVE ]] && export STTP_NATIVE=1
script:
  - [[ -n $IS_JS ]] && google-chrome --version
  - [[ -n $IS_JVM ]] && sbt compileDocs
  - [[ -n $IS_JVM ]] && sbt -v testJVM
  - [[ -n $IS_JS ]] && sbt -v testJS
  - [[ -n $IS_NATIVE ]] && sbt -v testNative
