language: scala
addons:
  chrome: stable
jdk:
- oraclejdk8
- openjdk11
dist: trusty
scala:
- 2.12.10
- 2.11.12
- 2.13.1
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
before_install:
  - bash project/travis_setup.sh
before_script:
- nvm install 10 # nodejs < 10 fails finding URL class
- version="$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)" &&
    wget "https://chromedriver.storage.googleapis.com/$version/chromedriver_linux64.zip"
- mkdir -p chromedriver && unzip chromedriver_linux64.zip -d chromedriver/
- export PATH="$PATH:$PWD/chromedriver/"
script:
- test $TRAVIS_JDK_VERSION = "oraclejdk8" && sbt ++$TRAVIS_SCALA_VERSION rootJVM/test &&
    xvfb-run sbt ++$TRAVIS_SCALA_VERSION rootJS/test &&
    sbt rootNative/test
- test $TRAVIS_JDK_VERSION = "openjdk11" && test $TRAVIS_SCALA_VERSION = "2.13.1" && sbt ++$TRAVIS_SCALA_VERSION java11backend/test
