language: scala
addons:
  chrome: stable
jdk:
- oraclejdk8
- openjdk11
dist: trusty
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
before_install:
  - if [[ ($TRAVIS_JDK_VERSION = "oraclejdk8") && ($TRAVIS_SCALA_VERSION =~ ^2.11.*) ]]; then bash project/travis_setup.sh; fi
before_script:
- nvm install 10 # nodejs < 10 fails finding URL class
script:
- sbt test
