language: scala
addons:
  chrome: stable
jdk:
  - openjdk11
dist: bionic
env:
  - BUILD_TYPE=jvm
  - BUILD_TYPE=js
  - BUILD_TYPE=native
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
before_install:
  - if [ $BUILD_TYPE == "native" ]; then bash project/travis_setup.sh; fi
before_script:
  - if [ $BUILD_TYPE == "js" ]; then nvm install 10; fi # nodejs < 10 fails finding URL class
  - if [ $BUILD_TYPE == "native" ]; then export STTP_NATIVE=1; fi
script:
  - if [ $BUILD_TYPE == "js" ]; then google-chrome --version; fi
  - if [ $BUILD_TYPE == "jvm" ]; then sbt compileDocs; fi
  - if [ $BUILD_TYPE == "jvm" ]; then sbt -v testJVM; fi
  - if [ $BUILD_TYPE == "js" ]; then sbt -v testJS; fi
  - if [ $BUILD_TYPE == "native" ]; then sbt -v testNative; fi
